[package]
name = "lowbulls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "master_benchmark"
harness = false
